apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: nginx

spec:
  containers:
  - name: toolbox
    image: busybox
    imagePullPolicy: IfNotPresent

    command:
    - sleep
    - "3600"