apiVersion: batch/v1
kind: Job

metadata:
  name: hello-job
  namespace: jobs-demo

spec:
  template:
    spec:
      restartPolicy: Never

      containers:
        - name: hello

          image: workshop-tools:arm64
          imagePullPolicy: IfNotPresent

          command:
            - /bin/sh
            - -c
            - |
              echo "Hello from Kubernetes Jobs!"
              sleep 5
              echo "Job complete."