site_name: Pocket-Sized Kubernetes 
nav:
- introduction.md
- designing-a-cluster.md
- Section 1 — Building your cluster:
  - Introduction: lesson1.md
  - Exercise 1 — Connecting to Your Nodes: lesson1/exercise1.md
  - Exercise 2 — Installing K3s and creating the cluster: lesson1/exercise2.md
  - Exercise 3 — Kubectl Basics: lesson1/exercise3.md
  - Lesson 1 summary: lesson1/summary.md
- Section 2 — Using your cluster:
  - Introduction: lesson2.md
  - Exercise 1 — Services, networking and Monitoring: 
      1a) Services and networking: lesson2/exercise1a.md
      1b) Monitoring and Telemetry: lesson2/exercise1b.md
  - Exercise 2 — Resource Management and Failure Recovery: lesson2/exercise2.md
  - Exercise 3 — Persistent Storage: lesson2/exercise3.md
  - Exercise 4 — Jobs and Batch Execution: lesson2/exercise4.md
- extra-reading.md
theme: 
  name: material
  palette:
    primary: teal
    accent: indigo
  logo: assets/CN-SIG-logo.png
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.footer
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - attr_list
  - md_in_html
copyright: © Cloud Native SIG 2026
repo_url: https://github.com/cloud-native-sig/hpcdays26-pocket-sized-kubernetes
edit_uri: edit/main/tutorial
site_url: https://cloud-native-sig.github.io/hpcdays26-pocket-sized-kubernetes/
